---
title:    "`r component.name <- 'спирта этилового';compound.name <- 'ВИТАСЕПТ-СКО';title <- paste0('Валидация методики количественного определения ',component.name,' в лекарственном средстве ',compound.name,', раствор спиртовой для наружного применения');title`"
author:   mz
date:     "`r Sys.time()`"
output:
  html_document:
    toc: true
    number_sections: true
---

```{r,echo=FALSE,results='hide'}
library(dplyr,quietly = TRUE,
        warn.conflicts = FALSE,
        logical.return = FALSE)
library(magrittr,quietly = TRUE,
        warn.conflicts = FALSE,
        logical.return = FALSE)
library(ggplot2,quietly = TRUE,
        warn.conflicts = FALSE,
        logical.return = FALSE)
library(tidyr,quietly = TRUE,
        warn.conflicts = FALSE,
        logical.return = FALSE)
library(xtable,quietly = TRUE,
        warn.conflicts = FALSE,
        logical.return = FALSE)
library(knitr,quietly = TRUE,
        warn.conflicts = FALSE,
        logical.return = FALSE)
```

# Назначение

Назначением валидации методики количественного определения `r component.name` в лекарственном средстве `r compound.name`, раствор спиртовой для наружного применения с детектированием методом --- является документальное подтверждение того, что методика воспроизводима в условиях лаборатории и результаты испытаний с использованием данной методики достоверны.

# Нормативные ссылки

Настоящий документ создан на основе следующих нормативных документов:

  1. СТБ ИСО 5725-(1-6)-2002 Часть 1-6 «Точность (правильность и прецизионность) методов и результатов измерений».
  1. СТП-1-0100-01 «Валидация методик испытания».
  1. ГФ РБ, т.1, стр.50, «…», 2006 г.
  1. CPMP/ICH Q2A TEXT ON VALIDATION OF ANALYTICAL PROCEDURES

# Общие требования

Результаты анализов должны быть внесены в тест-формы аналитических характеристик, каждая из которых должна быть подписана лицом, выполняющим испытание, и вторым лицом, подтверждающим полученные данные. 

Все отклонения от методики должны быть оформлены письменно. 

При получении неудовлетворительных результатов, должно быть выполнено повторное тестирование для исключения возможности лабораторной ошибки. В случае повторного неудовлетворительного результата – проведено исследование причины.

При необходимости в методику анализа должны быть внесены изменения. Соответствующие изменения вносятся в валидационный протокол метода анализа. Валидация методики выполняется повторно.

# Описание метода … и валидируемой методики анализа

# Оборудование и реактивы для испытаний

В работе использована насадочная металлическая колонка длиной 1 метр с внутренним диаметром 3 мм. **Насадка** – «Полисорб-1», фракция 0,1-0,2 мм. Условия газохроматографического определения. Хроматограф – «Кристалл-2000М» с пламенно-ионизационным детектором. Температура инжектора – 200 °С, колонки – 150 °С, детектора – 250 °С. Газ-носитель – азот, расход – 35 мл/мин, расход воздуха – 300 мл/мин, расход водорода – 30 мл/мин. Разметку выполняли с использованием прикладного программного обеспечения «Хроматек Аналитик 1.21» и «Хроматек Аналитик 1.5»

## Оборудование

## Реактивы

#  План валидации методики

При валидации данной методики исследования подлежат проверке следующие аналитические характеристики:

  1. специфичность (влияние плацебо) (Specificity);
  1. линейность (Linearity);
  1. прецизионность (Precision) внутрилабораторная прецизионность (Intermediate Precision) методики количественного определения лекарственного вещества;
  1. правильность (Accuracy);
  1. диапазон определяемых содержаний.

# Описание проведения испытаний

## Специфичность

Специфичность — это способность однозначно оценивать анализируемое вещество в присутствии других компонентов, которые могут присутствовать в образце. 

Специфичность оценивается путем исследования растворов лекарственного вещества, приготовленных с использованием растворов плацебо.

Критерий приемлемости:

  1. Величина аналитического сигнала, получаемого при исследовании плацебо не должна превышать по модулю более, чем на 2% значение аналитического сигнала, соответствующего нижней границе определяемых содержаний лекарственного вещества в лекарственном средстве.
  
## Линейность

Определение линейности методики проводится на пяти-восьми уровнях концентраций из предполагаемого диапазона определяемых содержаний.

Критерий приемлемости:
  
  1. Коэффициент **аппроксимации** $R^2$ должен быть не менее 0,999
  1. Значение средних рассчитанных содержаний аналита не должно отклоняться от истинного более чем на 2% .
  1. Значение свободного члена уравнения градуировочного графика по модулю не должно превышать 2% от аналитического сигнала, соответствующего 100% содержанию лекарственного вещества.

## Внутрилабораторная прецизионность

Внутрилабораторная прецизионность характеризует степень близости (разброса) результатов, полученных по разработанной методике.

Анализируются специально приготовленные образцы лекарственного средства (в разные дни), содержащие аналит в предполагаемом рабочем диапазоне разработанной методики (не менее трех на каждую концентрацию).

Критерий приемлемости:
  
  1. Коэффициент **вариации** (RSD) должен быть не более 2%.

## Правильность

Анализируются специально приготовленные образцы лекарственного средства (в разные дни), содержащие аналит в предполагаемом рабочем диапазоне разработанной методики (не менее трех на каждую концентрацию).

Критерий приемлемости:

  1. Среднее значение определяемых содержаний аналита должно отклоняться от истинного не более, чем на 2%.

## Диапазон определяемых содержаний

Диапазон определяемых содержаний устанавливается исходя из того, что валидируемая методика имеет приемлемую степень специфичности, линейности, правильности и внутрилабораторной прецизионности при анализе образцов с количественным содержанием аналита в диапазоне валидируемой методики.

По результатам валидационных процедур по п.п. 8.2-8.5 устанавливается линейный диапазон определяемых содержаний.

# Валидационный отчет

## Специфичность

### Исследование растворов плацебо

## Линейность

## Внутрилабораторная прецизионность

## Правильность

## Диапазон определяемых содержаний




